### ISSUE TITLE
Protected variable size taking unintended values

### ISSUE THREAD

**Issue by mksinha** [mksinha/MicrocontrollerSystem#5]
Size as a protected variable in Pinset class overshoots its desired value, but works if Public.

**Comment by AnimeshSinha1309** [comment]
Ideally, the code should look like this, but we needed to hardcode the value of `this->size` to avoid a bug and test temporarily.

``` C++
void Pinset::putData(unsigned int data) {
    for (int i = 0; i < this->size; i++, data /= 2) {
        Device::setDirection(pins[i], HIGH);
        if (data % 2 == HIGH)
            Device::setStatus(pins[i], HIGH);
        else
            Device::setStatus(pins[i], LOW);
    }
}
```

**Value of `this->size` is greater than 4**, the reason are yet to be debugged, and this causes the code to crash as the iteration loop exceeds the expected value and causes an _IndexOutOfBoundsException_.

Binary Examination of `this->size` show that it is **greater than 12 (0b1100)** and the last digits of its inary equivalent are **0b1100**. More on this variable needs to be found.

**Comment by AnimeshSinha1309** [comment]
Don't remember what happened, but the Pinset class works fins, so I think we are done with this issue now.
